@Journee_HostAddress = https://journee-xzmq.onrender.com

GET {{Journee_HostAddress}}/api/categories
Accept: application/json
[
  {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "userId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "categoryName": "string",
    "createdAt": "2025-12-13T09:19:27.072Z",
    "updatedAt": "2025-12-13T09:19:27.072Z"
  }
]
###

POST {{Journee_HostAddress}}/api/categories
Content-Type: application/json

{
  "userId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "categoryName": "string",
  "createdAt": "2025-12-13T09:19:27.074Z",
  "updatedAt": "2025-12-13T09:19:27.074Z"
}

###

POST {{Journee_HostAddress}}/api/categories
Content-Type: application/json

{
  //Category
}

###

GET {{Journee_HostAddress}}/api/categories

###

POST {{Journee_HostAddress}}/api/categories
Content-Type: application/json

{
  //Category
}

###

GET {{Journee_HostAddress}}/api/categories

###
